version: "3.8"

services:
  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - "8920:80"
