version: "3.7"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    image: imtkg
    volumes:
      - ./static:/app/static
    env_file:
      - .env.prod
  nginx:
    build: ./production/nginx
    volumes:
      - ./static:/app/static
    ports:
      - "443:443"
    depends_on:
      - web
