# Generated by Django 3.1.2 on 2020-11-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0002_auto_20201028_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='ar',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/img-tracking/data/videos/'),
        ),
    ]
