# Generated by Django 3.1.5 on 2021-01-16 09:47

import ar.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0003_auto_20210116_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=ar.storage.ImageStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ar',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='img-tracking/data/videos/'),
        ),
    ]
