# Generated by Django 3.1.5 on 2021-01-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0005_auto_20210123_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ar',
            name='in_progress',
        ),
    ]
