# Generated by Django 2.2.16 on 2021-03-11 15:05

import ar.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0006_remove_ar_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar',
            name='image',
            field=models.ImageField(storage=ar.storage.ImageStorage(), upload_to=''),
        ),
    ]
